spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: post-service-posts
            uri: http://${POST_SERVICE_HOST}:${POST_SERVICE_PORT}
            predicates:
              - Path=/posts/**
          - id: subscription-service-subscriptions
            uri: http://${SUBSCRIPTION_SERVICE_HOST}:${SUBSCRIPTION_SERVICE_PORT}
            predicates:
              - Path=/subscriptions/**
          - id: subscription-service-subscribers
            uri: http://${SUBSCRIPTION_SERVICE_HOST}:${SUBSCRIPTION_SERVICE_PORT}
            predicates:
              - Path=/subscribers/**
          - id: context-service-front-context
            uri: http://${CONTEXT_SERVICE_HOST}:${CONTEXT_SERVICE_PORT}
            predicates:
              - Path=/context/**