spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: post-service-posts
            uri: http://localhost:8081
            predicates:
              - Path=/posts/**
          - id: subscription-service-subscriptions
            uri: http://localhost:8082
            predicates:
              - Path=/subscriptions/**
          - id: subscription-service-subscribers
            uri: http://localhost:8082
            predicates:
              - Path=/subscribers/**
